@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk2MjQ0ODIsInVzZXJfaWQiOjF9.lq3R2zLpTWnsnKaWPksw0Ff8jxyPOqS6qcYCsuNfANg

###
POST http://localhost:8080/api/user/login
Content-Type: application/json
Accept-Encoding: gzip
{
    "login":"admin",
    "password":"admin"
}


POST http://localhost:8080/api/user/register
Content-Type: application/json
Accept-Encoding: gzip
{
    "login":"admin",
    "password":"admin"
}


POST http://localhost:8080/api/user/orders
Content-Type: text/plain
Authorization: {{token}}
12345678903

POST http://localhost:8080/api/user/orders
Content-Type: text/plain
authorization: {{token}}
109


GET http://localhost:8080/api/user/orders
authorization: {{token}}


GET http://localhost:8080/api/user/balance
authorization: {{token}}

GET http://localhost:8080/api/user/withdrawals
authorization: {{token}}

POST http://localhost:8080/api/user/balance/withdraw
authorization: {{token}}
Content-Type: application/json
{
    "order": "109",
    "sum": 100
}