// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/api/handle_get_user_balance.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	wallet "github.com/grizlaz/ya-gophermart/internal/domain/wallet"
)

// MockwalletGetService is a mock of walletGetService interface.
type MockwalletGetService struct {
	ctrl     *gomock.Controller
	recorder *MockwalletGetServiceMockRecorder
}

// MockwalletGetServiceMockRecorder is the mock recorder for MockwalletGetService.
type MockwalletGetServiceMockRecorder struct {
	mock *MockwalletGetService
}

// NewMockwalletGetService creates a new mock instance.
func NewMockwalletGetService(ctrl *gomock.Controller) *MockwalletGetService {
	mock := &MockwalletGetService{ctrl: ctrl}
	mock.recorder = &MockwalletGetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletGetService) EXPECT() *MockwalletGetServiceMockRecorder {
	return m.recorder
}

// GetUserBalance mocks base method.
func (m *MockwalletGetService) GetUserBalance(arg0 context.Context, arg1 int64) (*wallet.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", arg0, arg1)
	ret0, _ := ret[0].(*wallet.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockwalletGetServiceMockRecorder) GetUserBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockwalletGetService)(nil).GetUserBalance), arg0, arg1)
}
