// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/api/handle_get_user_orders.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	order "github.com/grizlaz/ya-gophermart/internal/domain/order"
)

// MockorderGetService is a mock of orderGetService interface.
type MockorderGetService struct {
	ctrl     *gomock.Controller
	recorder *MockorderGetServiceMockRecorder
}

// MockorderGetServiceMockRecorder is the mock recorder for MockorderGetService.
type MockorderGetServiceMockRecorder struct {
	mock *MockorderGetService
}

// NewMockorderGetService creates a new mock instance.
func NewMockorderGetService(ctrl *gomock.Controller) *MockorderGetService {
	mock := &MockorderGetService{ctrl: ctrl}
	mock.recorder = &MockorderGetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderGetService) EXPECT() *MockorderGetServiceMockRecorder {
	return m.recorder
}

// GetUserOrders mocks base method.
func (m *MockorderGetService) GetUserOrders(ctx context.Context, userID int64) ([]order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, userID)
	ret0, _ := ret[0].([]order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockorderGetServiceMockRecorder) GetUserOrders(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockorderGetService)(nil).GetUserOrders), ctx, userID)
}
