// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/api/handle_get_user_withdrawals.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	wallet "github.com/grizlaz/ya-gophermart/internal/domain/wallet"
)

// MockwalletWithdrawalsService is a mock of walletWithdrawalsService interface.
type MockwalletWithdrawalsService struct {
	ctrl     *gomock.Controller
	recorder *MockwalletWithdrawalsServiceMockRecorder
}

// MockwalletWithdrawalsServiceMockRecorder is the mock recorder for MockwalletWithdrawalsService.
type MockwalletWithdrawalsServiceMockRecorder struct {
	mock *MockwalletWithdrawalsService
}

// NewMockwalletWithdrawalsService creates a new mock instance.
func NewMockwalletWithdrawalsService(ctrl *gomock.Controller) *MockwalletWithdrawalsService {
	mock := &MockwalletWithdrawalsService{ctrl: ctrl}
	mock.recorder = &MockwalletWithdrawalsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletWithdrawalsService) EXPECT() *MockwalletWithdrawalsServiceMockRecorder {
	return m.recorder
}

// GetUserWithdrawals mocks base method.
func (m *MockwalletWithdrawalsService) GetUserWithdrawals(arg0 context.Context, arg1 int64) (*[]wallet.WalletHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithdrawals", arg0, arg1)
	ret0, _ := ret[0].(*[]wallet.WalletHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithdrawals indicates an expected call of GetUserWithdrawals.
func (mr *MockwalletWithdrawalsServiceMockRecorder) GetUserWithdrawals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithdrawals", reflect.TypeOf((*MockwalletWithdrawalsService)(nil).GetUserWithdrawals), arg0, arg1)
}
