// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/api/handle_user_register.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockuserRegisterService is a mock of userRegisterService interface.
type MockuserRegisterService struct {
	ctrl     *gomock.Controller
	recorder *MockuserRegisterServiceMockRecorder
}

// MockuserRegisterServiceMockRecorder is the mock recorder for MockuserRegisterService.
type MockuserRegisterServiceMockRecorder struct {
	mock *MockuserRegisterService
}

// NewMockuserRegisterService creates a new mock instance.
func NewMockuserRegisterService(ctrl *gomock.Controller) *MockuserRegisterService {
	mock := &MockuserRegisterService{ctrl: ctrl}
	mock.recorder = &MockuserRegisterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRegisterService) EXPECT() *MockuserRegisterServiceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockuserRegisterService) Register(ctx context.Context, login string, password [32]byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockuserRegisterServiceMockRecorder) Register(ctx, login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockuserRegisterService)(nil).Register), ctx, login, password)
}
