// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/api/handle_user_withdrawal.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockwalletWithdrawalService is a mock of walletWithdrawalService interface.
type MockwalletWithdrawalService struct {
	ctrl     *gomock.Controller
	recorder *MockwalletWithdrawalServiceMockRecorder
}

// MockwalletWithdrawalServiceMockRecorder is the mock recorder for MockwalletWithdrawalService.
type MockwalletWithdrawalServiceMockRecorder struct {
	mock *MockwalletWithdrawalService
}

// NewMockwalletWithdrawalService creates a new mock instance.
func NewMockwalletWithdrawalService(ctrl *gomock.Controller) *MockwalletWithdrawalService {
	mock := &MockwalletWithdrawalService{ctrl: ctrl}
	mock.recorder = &MockwalletWithdrawalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletWithdrawalService) EXPECT() *MockwalletWithdrawalServiceMockRecorder {
	return m.recorder
}

// BalanceWithdrawal mocks base method.
func (m *MockwalletWithdrawalService) BalanceWithdrawal(ctx context.Context, userID int64, number string, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BalanceWithdrawal", ctx, userID, number, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// BalanceWithdrawal indicates an expected call of BalanceWithdrawal.
func (mr *MockwalletWithdrawalServiceMockRecorder) BalanceWithdrawal(ctx, userID, number, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BalanceWithdrawal", reflect.TypeOf((*MockwalletWithdrawalService)(nil).BalanceWithdrawal), ctx, userID, number, amount)
}
