// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/api/handle_user_login.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockuserAuthService is a mock of userAuthService interface.
type MockuserAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockuserAuthServiceMockRecorder
}

// MockuserAuthServiceMockRecorder is the mock recorder for MockuserAuthService.
type MockuserAuthServiceMockRecorder struct {
	mock *MockuserAuthService
}

// NewMockuserAuthService creates a new mock instance.
func NewMockuserAuthService(ctrl *gomock.Controller) *MockuserAuthService {
	mock := &MockuserAuthService{ctrl: ctrl}
	mock.recorder = &MockuserAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserAuthService) EXPECT() *MockuserAuthServiceMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockuserAuthService) Auth(ctx context.Context, login string, password [32]byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockuserAuthServiceMockRecorder) Auth(ctx, login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockuserAuthService)(nil).Auth), ctx, login, password)
}
